env:
  num_rl_envs: 1
  num_planning_envs: 64
  env_spacing: 5.0

room:
  # Preset
  type: "custom"
  
  # Custom
  width: 5.0
  depth: 5.0

  obstacles:
    - type: "box"
      x: 0.0
      z: 0.0
      width: 1.0
      depth: 1.0
    - type: "box"
      x: 1.5
      z: 1.5
      width: 2.0
      depth: 0.5

sensors:
  enable_bumper: false
  enable_lidar: false
  enable_camera: false
  lidar_rays: 64
  camera_res: 64

robot:
  urdf_path: "roomba.urdf"
  radius: 0.17
  max_linear_velocity: 0.6   # m/s
  max_angular_velocity: 2.00  # rad/s
